version: '3.8'

services:
  canara_app:
    image: sky1912/canara_sky
    container_name: canara_app_sky
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    restart: always
